export const clearmaze= [

    [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ],
      [
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey"
      ]

];