export const maze = [
    [
      "lightgrey",
      "black",
      "lightgrey",
      "black",
      "black",
      "black",
      "black",
      "black",
      "black"
    ],
    [
      "lightgrey",
      "black",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "black",
      "black",
      "black"
    ],
    [
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "black",
      "black",
      "black",
      "black",
      "black",
      "black"
    ],
    [
      "black",
      "lightgrey",
      "lightgrey",
      "black",
      "black",
      "black",
      "black",
      "black",
      "black"
    ],
    [
      "black",
      "black",
      "lightgrey",
      "black",
      "black",
      "black",
      "black",
      "black",
      "black"
    ],
    [
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "black",
      "black",
      "lightgrey",
      "lightgrey"
    ],
    [
      "black",
      "black",
      "lightgrey",
      "black",
      "black",
      "black",
      "black",
      "lightgrey",
      "black"
    ],
    [
      "black",
      "black",
      "lightgrey",
      "black",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "lightgrey"
    ],
    [
      "black",
      "black",
      "lightgrey",
      "lightgrey",
      "lightgrey",
      "black",
      "black",
      "black",
      "lightgrey"
    ]
  ];